import { LotteryTest } from '../../typechain-types';

export const getPrize = async (proxy: LotteryTest) => {
  const [
    LAST_NUMBER,
    TWO_FIRST_NUMBER_AND_LAST_NUMBER,
    THREE_FIRST_NUMBER,
    THREE_FIRST_NUMBER_AND_LAST_NUMBER,
    FOUR_FIRST_NUMBER,
    FOUR_FIRST_NUMBER_AND_LAST_NUMBER,
    FIVE_FIRST_NUMBER,
    JACKPOT,
  ] = await Promise.all([
    proxy.LOTTERY_PRIZES_LAST_NUMBER(),
    proxy.LOTTERY_PRIZES_TWO_FIRST_NUMBER_AND_LAST_NUMBER(),
    proxy.LOTTERY_PRIZES_THREE_FIRST_NUMBER(),
    proxy.LOTTERY_PRIZES_THREE_FIRST_NUMBER_AND_LAST_NUMBER(),
    proxy.LOTTERY_PRIZES_FOUR_FIRST_NUMBER(),
    proxy.LOTTERY_PRIZES_FOUR_FIRST_NUMBER_AND_LAST_NUMBER(),
    proxy.LOTTERY_PRIZES_FIVE_FIRST_NUMBER(),
    proxy.LOTTERY_PRIZES_JACKPOT(),
  ]);

  return {
    LAST_NUMBER,
    TWO_FIRST_NUMBER_AND_LAST_NUMBER,
    THREE_FIRST_NUMBER,
    FOUR_FIRST_NUMBER,
    FOUR_FIRST_NUMBER_AND_LAST_NUMBER,
    FIVE_FIRST_NUMBER,
    JACKPOT,
    THREE_FIRST_NUMBER_AND_LAST_NUMBER,
  };
};
