/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BuyLotteryTicketTest } from "./BuyLotteryTicketTest";
export type { LotteryTest } from "./LotteryTest";
