/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as payableUupsUpgradableSol from './PayableUUPSUpgradable.sol';
export type { payableUupsUpgradableSol };
import type * as test from './test';
export type { test };
export type { Lottery } from './Lottery';
export type { LotteryDeclaration } from './LotteryDeclaration';
export type { LotteryState } from './LotteryState';
