export const MAP_PRIZE_TO_NUMBER = {
  NOT_LUCKY: 1,
  LAST_NUMBER: 2,
  TWO_FIRST_NUMBER_AND_LAST_NUMBER: 3,
  THREE_FIRST_NUMBER: 4,
  THREE_FIRST_NUMBER_AND_LAST_NUMBER: 5,
  FOUR_FIRST_NUMBER: 6,
  FOUR_FIRST_NUMBER_AND_LAST_NUMBER: 7,
  FIVE_FIRST_NUMBER: 8,
  JACKPOT: 9,
} as const;
