/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BuyLotteryTicketTest__factory } from './BuyLotteryTicketTest__factory';
export { LotteryTest__factory } from './LotteryTest__factory';
